import "./globals.css";
import type { Metadata } from "next";
import Modal from "@/components/AddModal";
import UpdateModal from "@/components/UpdateModal";

export const metadata: Metadata = {
  title: "Task Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#f5f6f8]">
        {children}
        <Modal />
        <UpdateModal />
      </body>
    </html>
  );
}
