import "./globals.css";
import { Nunito } from "next/font/google";
import type { Metadata } from "next";

import Modal from "@/components/AddModal";
import UpdateModal from "@/components/UpdateModal";

export const metadata: Metadata = {
  title: "Task Manager",
  description: "Generated by create next app",
};

export const font = Nunito({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${font.className} bg-[#f5f6f8]`}>
        {children}
        <Modal />
        <UpdateModal />
      </body>
    </html>
  );
}
