import "./globals.css";
import type { Metadata } from "next";

import Modal from "@/components/AddModal";
import UpdateModal from "@/components/UpdateModal";

export const metadata: Metadata = {
  title: "Task Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="bg-[#f5f6f8]">
        {children}
        <Modal />
        <UpdateModal />
      </body>
    </html>
  );
}
